// Code generated by github.com/likeawizard/exporter. DO NOT EDIT.

package repository

import "context"

type (
	Service     = service
	Repository  = repository
	UpdateQuery = updateQuery
	InsertQuery = insertQuery
)

const (
	ConnStr = connStr
)

var (
	ErrNotFound    = errNotFound
	ErrInvalidName = errInvalidName
	GetConnection  = getConnection
)

func (r Repository) Get(ctx context.Context, id int) (*Entity, error) {
	return r.get(ctx, id)
}
func (r *Repository) List() ([]Entity, error) {
	return r.list()
}
func (r *Repository) Create(q InsertQuery) (str string, err error) {
	return r.create(q)
}
func (r *Repository) Update(id int, partentID int, q UpdateQuery) (string, error) {
	return r.update(id, partentID, q)
}
func (r *Repository) Delete(id int) error {
	return r.delete(id)
}
