//go:build integration

// Code generated by github.com/likeawizard/exporter. DO NOT EDIT.

package repository

type (
	Repository  = repository
	UpdateQuery = updateQuery
	InsertQuery = insertQuery
)

const (
	ConnStr = connStr
)

var (
	ErrNotFound    = errNotFound
	ErrInvalidName = errInvalidName
	GetConnection  = getConnection
)

func (r Repository) Get(id int) (string, error) {
	return r.get(id)
}
func (r *Repository) Create(q InsertQuery) (string, error) {
	return r.create(q)
}
func (r *Repository) Update(id int, q UpdateQuery) (string, error) {
	return r.update(id, q)
}
func (r *Repository) Delete(id int) error {
	return r.delete(id)
}
